[general]
    executor = "slurm"
    data_dir = "$HOME"

[auth]
    downscope = "none"

[batch]
    scheduler_bin = "/opt/slurm/current/bin"
    env_vars = [
        "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/slurm/current/lib64:/opt/slurm/current/lib:/opt/slurm/current/lib/slurm:/cinecalocal/lib/slurm",
        "PATH=$PATH:/opt/slurm/current/bin:/opt/slurm/current/sbin"
    ]

